"use client"
import React, { useContext } from "react"
// import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import { Analytics } from "@vercel/analytics/next"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/utils/Sidebar"
import { Providers } from "./providers"
import {
  PlanTripProvider,
  RequestsMailsProvider,
} from "@/components/utils/ContextProvider"
import { usePathname } from "next/navigation"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

// metadata is for SEO optimization - this is admin panel so not needed
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const pathname = usePathname()
  const isLoginPage = pathname === "/login"
  const isForgotPasswordPage = pathname === "/forgot-password"
  const startPage = pathname === "/"

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
      >
        <PlanTripProvider>
          <RequestsMailsProvider>
            <Providers />
            <SidebarProvider>
              {!isLoginPage && !isForgotPasswordPage && !startPage && (
                <>
                  <AppSidebar />
                  <SidebarTrigger />
                </>
              )}

              {children}
              <Analytics />
            </SidebarProvider>
          </RequestsMailsProvider>
        </PlanTripProvider>
      </body>
    </html>
  )
}
